---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egressfox-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egressfox.io
  resources:
  - egressgateways
  - proxypools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - egressfox.io
  resources:
  - egressgateways/status
  - proxypools/status
  verbs:
  - get
  - patch
  - update
